In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

# Charger les fichiers CSV

In [3]:
folder_path = "/content/drive/MyDrive/Predicting-the-results-of-a-match"

In [4]:
games = pd.read_csv(folder_path+"/Data/games.csv")
teamstats = pd.read_csv(folder_path+"/Data/teamstats.csv")
print(f"Successfully loaded data")

Successfully loaded data

In [5]:
games.columns

Index(['gameID', 'leagueID', 'season', 'date', 'homeTeamID', 'awayTeamID',
       'homeGoals', 'awayGoals', 'homeProbability', 'drawProbability',
       'awayProbability', 'homeGoalsHalfTime', 'awayGoalsHalfTime', 'B365H',
       'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH',
       'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'PSCH', 'PSCD',
       'PSCA'],
      dtype='object')

In [6]:
games.head()

,gameID,leagueID,season,date,homeTeamID,awayTeamID,homeGoals,awayGoals,homeProbability,drawProbability,...,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA
0,81,1,2015,2015-08-08 15:45:00,89,82,1,0,0.2843,0.3999,...,5.90,1.62,3.6,6.00,1.67,4.00,5.75,1.64,4.07,6.04
1,82,1,2015,2015-08-08 18:00:00,73,71,0,1,0.3574,0.3500,...,4.27,1.91,3.5,4.00,2.00,3.50,4.20,1.82,3.88,4.70
2,83,1,2015,2015-08-08 18:00:00,72,90,2,2,0.2988,0.4337,...,5.62,1.73,3.5,5.00,1.73,3.90,5.40,1.75,3.76,5.44
3,84,1,2015,2015-08-08 18:00:00,75,77,4,2,0.6422,0.2057,...,4.34,2.00,3.1,2.70,2.00,3.40,4.33,1.79,3.74,5.10
4,85,1,2015,2015-08-08 18:00:00,79,78,1,3,0.1461,0.2159,...,3.08,2.60,3.1,2.88,2.60,3.25,3.00,2.46,3.39,3.14

In [7]:
teamstats.columns

Index(['gameID', 'teamID', 'season', 'date', 'location', 'goals', 'xGoals',
       'shots', 'shotsOnTarget', 'deep', 'ppda', 'fouls', 'corners',
       'yellowCards', 'redCards', 'result'],
      dtype='object')

In [8]:
teamstats.head()

,gameID,teamID,season,date,location,goals,xGoals,shots,shotsOnTarget,deep,ppda,fouls,corners,yellowCards,redCards,result
0,81,89,2015,2015-08-08 15:45:00,h,1,0.627539,9,1,4,13.8261,12,1,2.0,0,W
1,81,82,2015,2015-08-08 15:45:00,a,0,0.674600,9,4,10,8.2188,12,2,3.0,0,L
2,82,73,2015,2015-08-08 18:00:00,h,0,0.876106,11,2,11,6.9000,13,6,3.0,0,L
3,82,71,2015,2015-08-08 18:00:00,a,1,0.782253,7,3,2,11.8462,13,3,4.0,0,W
4,83,72,2015,2015-08-08 18:00:00,h,2,0.604226,10,5,5,6.6500,7,8,1.0,0,D

# Séparer stats domicile / extérieur

In [9]:
home_stats = teamstats[teamstats['location']=='h'].copy()
away_stats = teamstats[teamstats['location']=='a'].copy()

In [10]:
home_stats.head()

,gameID,teamID,season,date,location,goals,xGoals,shots,shotsOnTarget,deep,ppda,fouls,corners,yellowCards,redCards,result
0,81,89,2015,2015-08-08 15:45:00,h,1,0.627539,9,1,4,13.8261,12,1,2.0,0,W
2,82,73,2015,2015-08-08 18:00:00,h,0,0.876106,11,2,11,6.9000,13,6,3.0,0,L
4,83,72,2015,2015-08-08 18:00:00,h,2,0.604226,10,5,5,6.6500,7,8,1.0,0,D
6,84,75,2015,2015-08-08 18:00:00,h,4,2.568030,19,8,5,10.8800,13,6,2.0,0,W
8,85,79,2015,2015-08-08 18:00:00,h,1,1.130760,17,6,5,5.7368,14,1,1.0,0,L

In [11]:
away_stats.head()

,gameID,teamID,season,date,location,goals,xGoals,shots,shotsOnTarget,deep,ppda,fouls,corners,yellowCards,redCards,result
1,81,82,2015,2015-08-08 15:45:00,a,0,0.674600,9,4,10,8.2188,12,2,3.0,0,L
3,82,71,2015,2015-08-08 18:00:00,a,1,0.782253,7,3,2,11.8462,13,3,4.0,0,W
5,83,90,2015,2015-08-08 18:00:00,a,2,0.557892,11,5,4,17.1579,13,2,2.0,0,D
7,84,77,2015,2015-08-08 18:00:00,a,2,1.459460,11,5,6,9.5556,17,3,4.0,0,L
9,85,78,2015,2015-08-08 18:00:00,a,3,2.109750,11,7,10,10.6250,20,4,0.0,0,W

# Renommer colonnes

In [12]:
home_stats = home_stats.add_prefix('home_')
away_stats = away_stats.add_prefix('away_')

In [13]:
home_stats.head()

,home_gameID,home_teamID,home_season,home_date,home_location,home_goals,home_xGoals,home_shots,home_shotsOnTarget,home_deep,home_ppda,home_fouls,home_corners,home_yellowCards,home_redCards,home_result
0,81,89,2015,2015-08-08 15:45:00,h,1,0.627539,9,1,4,13.8261,12,1,2.0,0,W
2,82,73,2015,2015-08-08 18:00:00,h,0,0.876106,11,2,11,6.9000,13,6,3.0,0,L
4,83,72,2015,2015-08-08 18:00:00,h,2,0.604226,10,5,5,6.6500,7,8,1.0,0,D
6,84,75,2015,2015-08-08 18:00:00,h,4,2.568030,19,8,5,10.8800,13,6,2.0,0,W
8,85,79,2015,2015-08-08 18:00:00,h,1,1.130760,17,6,5,5.7368,14,1,1.0,0,L

In [14]:
away_stats.head()

,away_gameID,away_teamID,away_season,away_date,away_location,away_goals,away_xGoals,away_shots,away_shotsOnTarget,away_deep,away_ppda,away_fouls,away_corners,away_yellowCards,away_redCards,away_result
1,81,82,2015,2015-08-08 15:45:00,a,0,0.674600,9,4,10,8.2188,12,2,3.0,0,L
3,82,71,2015,2015-08-08 18:00:00,a,1,0.782253,7,3,2,11.8462,13,3,4.0,0,W
5,83,90,2015,2015-08-08 18:00:00,a,2,0.557892,11,5,4,17.1579,13,2,2.0,0,D
7,84,77,2015,2015-08-08 18:00:00,a,2,1.459460,11,5,6,9.5556,17,3,4.0,0,L
9,85,78,2015,2015-08-08 18:00:00,a,3,2.109750,11,7,10,10.6250,20,4,0.0,0,W

# Fusion avec games

In [15]:
df = games.merge(home_stats, left_on=['gameID','homeTeamID'], right_on=['home_gameID','home_teamID'])
df = df.merge(away_stats, left_on=['gameID','awayTeamID'], right_on=['away_gameID','away_teamID'])

In [16]:
df.head()

,gameID,leagueID,season,date,homeTeamID,awayTeamID,homeGoals,awayGoals,homeProbability,drawProbability,...,away_xGoals,away_shots,away_shotsOnTarget,away_deep,away_ppda,away_fouls,away_corners,away_yellowCards,away_redCards,away_result
0,81,1,2015,2015-08-08 15:45:00,89,82,1,0,0.2843,0.3999,...,0.674600,9,4,10,8.2188,12,2,3.0,0,L
1,82,1,2015,2015-08-08 18:00:00,73,71,0,1,0.3574,0.3500,...,0.782253,7,3,2,11.8462,13,3,4.0,0,W
2,83,1,2015,2015-08-08 18:00:00,72,90,2,2,0.2988,0.4337,...,0.557892,11,5,4,17.1579,13,2,2.0,0,D
3,84,1,2015,2015-08-08 18:00:00,75,77,4,2,0.6422,0.2057,...,1.459460,11,5,6,9.5556,17,3,4.0,0,L
4,85,1,2015,2015-08-08 18:00:00,79,78,1,3,0.1461,0.2159,...,2.109750,11,7,10,10.6250,20,4,0.0,0,W

# Définir target

In [17]:
def match_result(row):
    if row['homeGoals'] > row['awayGoals']:
        return 'Home Win'
    elif row['homeGoals'] < row['awayGoals']:
        return 'Away Win'
    else:
        return 'Draw'

In [18]:
df['target'] = df.apply(match_result, axis=1)

In [19]:
df.head()

,gameID,leagueID,season,date,homeTeamID,awayTeamID,homeGoals,awayGoals,homeProbability,drawProbability,...,away_shots,away_shotsOnTarget,away_deep,away_ppda,away_fouls,away_corners,away_yellowCards,away_redCards,away_result,target
0,81,1,2015,2015-08-08 15:45:00,89,82,1,0,0.2843,0.3999,...,9,4,10,8.2188,12,2,3.0,0,L,Home Win
1,82,1,2015,2015-08-08 18:00:00,73,71,0,1,0.3574,0.3500,...,7,3,2,11.8462,13,3,4.0,0,W,Away Win
2,83,1,2015,2015-08-08 18:00:00,72,90,2,2,0.2988,0.4337,...,11,5,4,17.1579,13,2,2.0,0,D,Draw
3,84,1,2015,2015-08-08 18:00:00,75,77,4,2,0.6422,0.2057,...,11,5,6,9.5556,17,3,4.0,0,L,Home Win
4,85,1,2015,2015-08-08 18:00:00,79,78,1,3,0.1461,0.2159,...,11,7,10,10.6250,20,4,0.0,0,W,Away Win

# Colonnes finales

In [20]:
features = [
    'season','leagueID',
    'home_goals','home_xGoals','home_shots','home_shotsOnTarget','home_corners','home_ppda','home_yellowCards','home_redCards',
    'away_goals','away_xGoals','away_shots','away_shotsOnTarget','away_corners','away_ppda','away_yellowCards','away_redCards',
    'target'
]

In [21]:
final_dataset = df[features]

In [22]:
final_dataset.head()

,season,leagueID,home_goals,home_xGoals,home_shots,home_shotsOnTarget,home_corners,home_ppda,home_yellowCards,home_redCards,away_goals,away_xGoals,away_shots,away_shotsOnTarget,away_corners,away_ppda,away_yellowCards,away_redCards,target
0,2015,1,1,0.627539,9,1,1,13.8261,2.0,0,0,0.674600,9,4,2,8.2188,3.0,0,Home Win
1,2015,1,0,0.876106,11,2,6,6.9000,3.0,0,1,0.782253,7,3,3,11.8462,4.0,0,Away Win
2,2015,1,2,0.604226,10,5,8,6.6500,1.0,0,2,0.557892,11,5,2,17.1579,2.0,0,Draw
3,2015,1,4,2.568030,19,8,6,10.8800,2.0,0,2,1.459460,11,5,3,9.5556,4.0,0,Home Win
4,2015,1,1,1.130760,17,6,1,5.7368,1.0,0,3,2.109750,11,7,4,10.6250,0.0,0,Away Win

In [23]:
final_dataset['target_code'] = df['target'].map({'Home Win':0,'Draw':1,'Away Win':2})

/tmp/ipython-input-3832123577.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset['target_code'] = df['target'].map({'Home Win':0,'Draw':1,'Away Win':2})

In [24]:
final_dataset.to_csv(folder_path+"/Data/dataset_match_classification.csv", index=False)